### ISSUE TITLE
Authentication Issue - SSH session not active

### ISSUE THREAD

**Issue by jrschneider** [napalm-automation-community/napalm-aos#24]
```
NAPALM didn't catch this exception. Please, fill a bugfix on https://github.com/napalm-automation/napalm/issues
Don't forget to include this traceback.
Traceback (most recent call last):
  File "check_broadcast_storm.py", line 94, in <module>
    delta_counters = check_broadcast_storm(device, interval=args.interval, alarm_threshold=args.alarm_threshold)
  File "check_broadcast_storm.py", line 16, in check_broadcast_storm
    new_counters = device.get_interfaces_counters()
  File "/home/disturbedmime/lib/cpp-py3/lib/python3.6/site-packages/napalm_aos/aos.py", line 490, in get_interfaces_counters
    stdout = self.device.send_command(command)
  File "/home/disturbedmime/lib/cpp-py3/lib/python3.6/site-packages/napalm_aos/utils/AlcatelOS.py", line 151, in send_command
    output, error, retCode = self.send_command_std(command, timeout, throw_exception)
  File "/home/disturbedmime/lib/cpp-py3/lib/python3.6/site-packages/napalm_aos/utils/AlcatelOS.py", line 159, in send_command_std
    chan = self.ssh.get_transport().open_session()
  File "/home/disturbedmime/lib/cpp-py3/lib/python3.6/site-packages/paramiko/transport.py", line 806, in open_session
    timeout=timeout,
  File "/home/disturbedmime/lib/cpp-py3/lib/python3.6/site-packages/paramiko/transport.py", line 896, in open_channel
    raise SSHException("SSH session not active")
paramiko.ssh_exception.SSHException: SSH session not active
```

The exception is being raised by napalm_aos, so I decided to file here rather than against napalm itself. Let me know if I should file against them.

As an interesting aside, the switch locks out a standard SSH connection for a short time, not offering any authentication methods. Seems to resolve itself after 15 or so seconds, but manual login directly after the script runs is unsuccessful until some small period of time has passed.

Switch: OS6450-P10
OS Version: 6.7.2.191.R04 GA

$ pip freeze | grep napalm
napalm==2.4.0
napalm-aos==0.1.1
napalm-panos==0.5.2

Python 3.6.7 - Ubuntu 18.04.2 LTS

I realize that napalm_aos is only supported against AOS8, but I figured I would give it a shot anyway. I'm not entirely sure what is breaking under the hood. Works fine against AOS8 devices.

**Comment by jrschneider** [comment]
Well that didn't format very well...

```
NAPALM didn't catch this exception. Please, fill a bugfix on https://github.com/napalm-automation/napalm/issues
Don't forget to include this traceback.
Traceback (most recent call last):
  File "check_broadcast_storm.py", line 94, in <module>
    delta_counters = check_broadcast_storm(device, interval=args.interval, alarm_threshold=args.alarm_threshold)
  File "check_broadcast_storm.py", line 16, in check_broadcast_storm
    new_counters = device.get_interfaces_counters()
  File "/home/disturbedmime/lib/cpp-py3/lib/python3.6/site-packages/napalm_aos/aos.py", line 490, in get_interfaces_counters
    stdout = self.device.send_command(command)
  File "/home/disturbedmime/lib/cpp-py3/lib/python3.6/site-packages/napalm_aos/utils/AlcatelOS.py", line 151, in send_command
    output, error, retCode = self.send_command_std(command, timeout, throw_exception)
  File "/home/disturbedmime/lib/cpp-py3/lib/python3.6/site-packages/napalm_aos/utils/AlcatelOS.py", line 159, in send_command_std
    chan = self.ssh.get_transport().open_session()
  File "/home/disturbedmime/lib/cpp-py3/lib/python3.6/site-packages/paramiko/transport.py", line 806, in open_session
    timeout=timeout,
  File "/home/disturbedmime/lib/cpp-py3/lib/python3.6/site-packages/paramiko/transport.py", line 896, in open_channel
    raise SSHException("SSH session not active")
paramiko.ssh_exception.SSHException: SSH session not active
```

**Comment by vmuthukrishnan** [comment]
NAPALM is supported against AOS8 only. Against which version are you trying?

**Comment by jrschneider** [comment]
Sorry, I edited the original post with more information.

**Comment by vmuthukrishnan** [comment]
NAPALM is not supported on AOS6 devices.  6.7.2.191.R04 is not supported.
