### ISSUE TITLE
No Class Inhereting napalm.base.base.NetworkDriver

### ISSUE THREAD

**Issue by shibumi** [napalm-automation-community/napalm-aos#3]
Hey,
I got some weird error with napalm-aos 1.0
```
>>> from napalm import get_network_driver
>>> get_network_driver("aos")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/bla/.virtualenvs/ansible/lib/python3.6/site-packages/napalm/base/__init__.py", line 116, in get_network_driver
    .format(install_name=module_install_name))
napalm.base.exceptions.ModuleImportError: No class inheriting "napalm.base.base.NetworkDriver" found in "napalm.aos".
>>>
```

**Comment by vmuthukrishnan** [comment]
We have resolved this. Could you check and confirm?

**Comment by shibumi** [comment]
@vmuthukrishnan yep I can confirm. This works as expected now:
```
>>> from napalm import get_network_driver
>>> get_network_driver("aos")
<class 'napalm_aos.aos.AOSDriver'>
>>> 
```
